version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.14.2-alpine
    restart: always
    links:
      - "dtex-fe:dtex-fe"
      - "dtex-be:dtex-be"
    depends_on:
      - "dtex-fe"
      - "dtex-be"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d/
      - ./certbot-fe/conf/:/etc/nginx/ssl/fe/
      - ./certbot-fe/data:/usr/share/nginx/fe/html/letsencrypt
      - ./certbot-be/conf/:/etc/nginx/ssl/be/
      - ./certbot-be/data:/usr/share/nginx/be/html/letsencrypt

  dtex-fe:
    container_name: dtex-fe
    image: thang268/dtex-fe:latest
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dtex-be:
    container_name: dtex-be
    image: thang268/dtex-be:latest
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot-fe:
    image: "infinityofspace/certbot_dns_duckdns:latest"
    container_name: "certbot-fe"
    volumes:
      - ./certbot-fe/conf/:/etc/letsencrypt
      - ./certbot-fe/logs/:/var/log/letsencrypt
      - ./certbot-fe/data:/usr/share/nginx/fe/html/letsencrypt
    command: certonly
      --non-interactive
      --agree-tos
      --email luongthangg268@gmail.com
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token 9bf4842e-2f56-4cd5-8574-6dc1782d32cb
      --dns-duckdns-propagation-seconds 30
      -d dtex.duckdns.org
      --staging

  certbot-be:
    image: "infinityofspace/certbot_dns_duckdns:latest"
    container_name: "certbot-be"
    volumes:
      - ./certbot-be/conf/:/etc/letsencrypt
      - ./certbot-be/logs/:/var/log/letsencrypt
      - ./certbot-be/data:/usr/share/nginx/be/html/letsencrypt
    command: certonly
      --non-interactive
      --agree-tos
      --email luongthangg268@gmail.com
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token 9bf4842e-2f56-4cd5-8574-6dc1782d32cb
      --dns-duckdns-propagation-seconds 30
      -d dtex-api.duckdns.org
      --staging
  

      