version: '3.7'

services:
  helloworld:
      container_name: helloworld
      image: crccheck/hello-world
  
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/nginx/ssl/
      # - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

    # command: certonly --webroot -w /var/www/certbot --force-renewal --email luongthangg268@gmail.com -d lxt.duckdns.org --agree-tos
