version: '3.7'

services:
  helloworld:
      container_name: helloworld
      image: crccheck/hello-world
      expose:
          - 8000

  certbot:
    image: "infinityofspace/certbot_dns_duckdns:latest"
    container_name: "certbot_dns_duckdns"
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    command: certonly
      --non-interactive
      --agree-tos
      --email luongthangg268@gmail.com
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token 9bf4842e-2f56-4cd5-8574-6dc1782d32cb
      --dns-duckdns-propagation-seconds 30
      -d dtex.duckdns.org
    
  nginx:
    image: nginx:1.14.2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d/
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - helloworld
      - certbot

      